[package]
name = "rust-node-napi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
crossbeam-channel = "0.5.6"
napi = "2"
napi-derive = "2"
once_cell = "1"

[build-dependencies]
napi-build = "1"
